/**
 * ATT&CK Navigator layer export: technique scores = number of Sigma rules in
 * the catalog referencing each (sub-)technique. Import this file directly in
 * https://mitre-attack.github.io/attack-navigator/ ("Open Existing Layer →
 * Upload from local").
 */
import type { APIRoute } from 'astro';
import matrix from '../data/attack-matrix.json';
import metadata from '../generated/source-metadata.json';
import { SITE_NAME, canonical } from '../lib/site';
import type { SigmaRule } from '../lib/sigma';

export const GET: APIRoute = async () => {
  const { default: rules } = (await import('../generated/rules.json')) as { default: SigmaRule[] };

  const counts = new Map<string, number>();
  for (const rule of rules) {
    for (const id of new Set([...rule.mitreTechniques, ...rule.mitreSubTechniques])) {
      counts.set(id, (counts.get(id) ?? 0) + 1);
    }
  }

  const techniques = [...counts.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([techniqueID, score]) => ({
      techniqueID,
      score,
      comment: `${score} Sigma rule${score === 1 ? '' : 's'} in the catalog`,
    }));

  const layer = {
    name: `${SITE_NAME} coverage`,
    versions: { attack: matrix.version, navigator: '5.1.0', layer: '4.5' },
    domain: 'enterprise-attack',
    description:
      `Number of Sigma rules per ATT&CK technique, from ${metadata.repo}@${metadata.commit.slice(0, 12)} ` +
      `(synced ${metadata.syncedAt.slice(0, 10)}). Generated by ${canonical('/')}`,
    sorting: 3,
    layout: { layout: 'side', showID: true, showName: true },
    hideDisabled: false,
    techniques,
    gradient: {
      colors: ['#f4f4f5', '#99f6e4', '#0f766e'],
      minValue: 0,
      maxValue: Math.max(1, ...techniques.map((t) => t.score)),
    },
    metadata: [
      { name: 'source', value: `https://github.com/${metadata.repo}` },
      { name: 'commit', value: metadata.commit },
      { name: 'generated by', value: canonical('/') },
    ],
  };

  return new Response(JSON.stringify(layer, null, 2), {
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  });
};
